// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import React from 'react';
import { Suspense } from 'react';
import type { Metadata, Viewport } from 'next';
import '@/styles/index.css';
import WhatsAppButton from '@/components/common/WhatsAppButton';
import { BUSINESS_INFO } from '@/constants/business';

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
};

export const metadata: Metadata = {
  metadataBase: new URL('https://vkfans.com'),
  title: {
    default: `${BUSINESS_INFO.name} - Premium Industrial & Domestic Fans`,
    template: `%s | ${BUSINESS_INFO.name}`,
  },
  description: BUSINESS_INFO.seo.description,
  authors: [{ name: BUSINESS_INFO.name, url: 'https://vkfans.com' }],
  creator: BUSINESS_INFO.name,
  publisher: BUSINESS_INFO.name,
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: 'website',
    locale: 'en_IN',
    url: 'https://vkfans.com',
    siteName: BUSINESS_INFO.name,
    title: `${BUSINESS_INFO.name} - Industrial & Domestic Fans`,
    description: BUSINESS_INFO.seo.description,
  },
  twitter: {
    card: 'summary_large_image',
    title: `${BUSINESS_INFO.name} - Premium Fans`,
    description: BUSINESS_INFO.seo.description,
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'your-google-verification-code',
  },
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head>
        <link rel="canonical" href="https://vkfans.com" />
        <meta name="geo.region" content="IN-DL" />
        <meta name="geo.placename" content="Delhi" />
        <meta name="geo.position" content="28.8386;77.0914" />
        <meta name="ICBM" content="28.8386, 77.0914" />

        <script type="module" async src="https://static.rocket.new/rocket-web.js?_cfg=https%3A%2F%2Findustrial8713back.builtwithrocket.new&_be=https%3A%2F%2Fapplication.rocket.new&_v=0.1.11" />
        <script type="module" defer src="https://static.rocket.new/rocket-shot.js?v=0.0.1" /></head>
      <body>
        <Suspense fallback={null}>{children}</Suspense>
        <WhatsAppButton />
      </body>
    </html>
  );
}
