// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import React from 'react';
import { Suspense } from 'react';
import { Inter, JetBrains_Mono } from 'next/font/google';
import type { Metadata, Viewport } from 'next';
import '@/styles/index.css';
import WhatsAppButton from '@/components/common/WhatsAppButton';
import { BUSINESS_INFO } from '@/constants/business';

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
};

export const metadata: Metadata = {
  metadataBase: new URL('https://vkfans.com'),
  title: {
    default: `${BUSINESS_INFO.name} - Premium Industrial & Domestic Fans Manufacturer in Delhi`,
    template: `%s | ${BUSINESS_INFO.name}`,
  },
  description: BUSINESS_INFO.seo.description,
  keywords: BUSINESS_INFO.seo.keywords.join(', '),
  authors: [{ name: BUSINESS_INFO.name, url: 'https://vkfans.com' }],
  creator: BUSINESS_INFO.name,
  publisher: BUSINESS_INFO.name,
  icons: {
    icon: '/favicon.svg',
    shortcut: '/favicon.svg',
    apple: '/favicon.svg',
  },
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: 'website',
    locale: 'en_IN',
    url: 'https://vkfans.com',
    siteName: BUSINESS_INFO.name,
    title: `${BUSINESS_INFO.name} - Industrial & Domestic Fans Manufacturer`,
    description: BUSINESS_INFO.seo.description,
    images: [
      {
        url: 'https://vkfans.com/og-image.jpg',
        width: 1200,
        height: 630,
        alt: `${BUSINESS_INFO.name} - Premium Fans`,
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: `${BUSINESS_INFO.name} - Premium Industrial & Domestic Fans`,
    description: BUSINESS_INFO.seo.description,
    creator: '@vkfans',
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'your-google-verification-code',
    other: {
      'msvalidate.01': 'your-bing-verification-code',
    },
  },
  alternates: {
    canonical: 'https://vkfans.com',
  },
};

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

const jetbrains = JetBrains_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-jetbrains',
});

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" data-gramm="false" data-gramm_editor="false">
      <head>
        <link rel="canonical" href="https://vkfans.com" />
        <link rel="preconnect" href="https://img.rocket.new" crossOrigin="" />
        <link rel="preconnect" href="https://images.unsplash.com" crossOrigin="" />
        
        {/* Geo-targeting for local SEO */}
        <meta name="geo.region" content="IN-DL" />
        <meta name="geo.placename" content="Delhi, India" />
        <meta name="geo.position" content="28.8386;77.0914" />
        <meta name="ICBM" content="28.8386, 77.0914" />
        
        {/* Sitemap and RSS */}
        <link rel="sitemap" href="/sitemap.xml" />
        <link rel="alternate" type="application/rss+xml" href="/feed.xml" />
        
        {/* Additional SEO meta tags */}
        <meta name="language" content="English" />
        <meta name="revisit-after" content="7 days" />
        <meta name="author" content="VK Fans" />
        <meta name="distribution" content="global" />
      </head>
      <body suppressHydrationWarning className={`${inter.variable} ${jetbrains.variable}`}>
        <Suspense fallback={null}>{children}</Suspense>
        <WhatsAppButton />
      </body>
    </html>
  );
}
